/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface FizzBuzz {
    'buzz': string;
    'buzzColor': string;
    'fizz': string;
    'fizzColor': string;
    'maximum': number;
    'start': number;
  }
  interface FizzBuzzAttributes extends StencilHTMLAttributes {
    'buzz'?: string;
    'buzzColor'?: string;
    'fizz'?: string;
    'fizzColor'?: string;
    'maximum'?: number;
    'start'?: number;
  }

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'FizzBuzz': Components.FizzBuzz;
    'MyComponent': Components.MyComponent;
  }

  interface StencilIntrinsicElements {
    'fizz-buzz': Components.FizzBuzzAttributes;
    'my-component': Components.MyComponentAttributes;
  }


  interface HTMLFizzBuzzElement extends Components.FizzBuzz, HTMLStencilElement {}
  var HTMLFizzBuzzElement: {
    prototype: HTMLFizzBuzzElement;
    new (): HTMLFizzBuzzElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLElementTagNameMap {
    'fizz-buzz': HTMLFizzBuzzElement
    'my-component': HTMLMyComponentElement
  }

  interface ElementTagNameMap {
    'fizz-buzz': HTMLFizzBuzzElement;
    'my-component': HTMLMyComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
